### ISSUE TITLE
Novick's Café Issues

### ISSUE THREAD

**Issue by thisjustin123** [cuappdev/eatery-blue-android#27]
Novick's Cafe is behaving very strangely and causes a crash.

- Novick's Café causes a crash when scrolled by.
- Novick's Café is not alphabetically ordered correctly.
- Novick's Café crashes when favorited.

My best guess is that the Novick's Café Eatery object is created from a malformed backend response that our code isn't designed to handle.

Steps to reproduce:

1. Find Novick's Café on the main screen. (Is likely found at the very top since it's not being alphabetically ordered correctly)
2. Very slowly scroll up.
3. When Novick's Café is about to go out of view, a crash occurs.
4. Favorite Novick's Café. A crash should occur.

**Comment by ckdesir** [comment]
I think this may be because Novick's Café does not have an ID
