### ISSUE TITLE
Menu spacing

### ISSUE THREAD

**Issue by thisjustin123** [cuappdev/eatery-blue-android#61]
Eatery detail screen menu lines are almost definitely not correct. This looks jank af:

![Screenshot_20240214-235128](https://github.com/cuappdev/eatery-blue-android/assets/47724806/5002ec65-1d9b-4c57-8c8a-7ba87960e30c)

**Comment by oliviaxjiang** [comment]
some menu items have lines below them while some don't, also there isn't a gap between each category as per the figma design
