### ISSUE TITLE
Open hours wrong: Upcoming Menus

### ISSUE THREAD

**Issue by thisjustin123** [cuappdev/eatery-blue-android#64]
This screenshot was taken at 11:57pm. These dining halls shown definitely shouldn't be open.

![Screenshot_20240214-235722](https://github.com/cuappdev/eatery-blue-android/assets/47724806/2aae641b-8956-4c32-92c4-89cf3d20f53b)

**Comment by Gregor-Guerrier** [comment]
This is because you have the Breakfast Filter enabled. SMH
