### ISSUE TITLE
Eatery Details Top Bar

### ISSUE THREAD

**Issue by oliviaxjiang** [cuappdev/eatery-blue-android#98]
Once the user scrolls down on the eatery details screen (and the title of the eatery can no longer been visible), there should be a top bar (see image below) detailing the name of the eatery, the favorite button, as well as a nav bar of the different categories of food items.
<img width="224" alt="Screenshot 2024-03-04 at 2 05 26 PM" src="https://github.com/cuappdev/eatery-blue-android/assets/149902487/8d09685b-eb89-4bd5-a36d-165481d47ff8">

**Comment by thisjustin123** [comment]
(We'll target this post-launch; seems like a good feature but unnecessary for launch for now!)
